apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0001
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 storageClassName: slow
 hostPath:
  path: /var/lib/minishift/openshift.local.volumes/pv0001
